[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "python-telegram-bot==21.7",
    "sqlalchemy>=2.0.41",
    "telegram>=0.0.1",
    "yt-dlp>=2025.7.21",
]
